name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "prerel", "prerel-*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: prune container registry
      uses: actions/delete-package-versions@v5
      with:
        package-name: "${{ github.event.repository.name }}"
        package-type: 'container'
        min-versions-to-keep: 3
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Add additional ids
      id: myids
      run: |
        echo "${{ steps.meta.outputs.tags }}"
        (
          cat ./version.mk
          echo IMAGE_NAME="$(echo '${{ env.IMAGE_NAME }}' | tr A-Z a-z)"
          echo DATE=$(date +'%Y%m%d')
        ) >> $GITHUB_OUTPUT
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.REGISTRY }}/${{ steps.myids.outputs.IMAGE_NAME }}:${{ steps.myids.outputs.DATE }}
          ${{ env.REGISTRY }}/${{ steps.myids.outputs.IMAGE_NAME }}:${{ steps.myids.outputs.PYINSTALLER_VERSION }}-py${{ steps.myids.outputs.PYTHON_VERSION }}-upx${{ steps.myids.outputs.UPX_VERSION }}-${{ steps.myids.outputs.DATE }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PYTHON_VERSION=${{ steps.myids.outputs.PYTHON_VERSION }}
          PYINSTALLER_VERSION=${{ steps.myids.outputs.PYINSTALLER_VERSION }}
          UPX_VERSION=${{ steps.myids.outputs.UPX_VERSION }}
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
